apiVersion: 1

datasources:
  - name: Loki
    
    type: loki
    access: proxy
    
    orgId: 1
    uid: uid-example
    
    url: http://loki:3100
    isDefault: true
    
    version: 1
    editable: false
